"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['HistoricalWeather.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'icons.icns', 'resources': 'stations.csv'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
